export const themes = [
  {
    name: "light",
    primary: "#ffffff",
    secondary: "#f3f4f6",
    tertiary: "#e5e7eb",
    quaternary: "#d1d5db",
  },
  {
    name: "dark",
    primary: "#1e1e1e",
    secondary: "#252525",
    tertiary: "#3d3d3d",
    quaternary: "#575757",
  },
  {
    name: "cupcake",
    primary: "#fbd1e2",
    secondary: "#fde6f2",
    tertiary: "#f8d7da",
    quaternary: "#f3bcc8",
  },
  {
    name: "bumblebee",
    primary: "#fbee8a",
    secondary: "#f9d923",
    tertiary: "#ffd60a",
    quaternary: "#ffcc33",
  },
  {
    name: "emerald",
    primary: "#10b981",
    secondary: "#34d399",
    tertiary: "#6ee7b7",
    quaternary: "#a7f3d0",
  },
  {
    name: "corporate",
    primary: "#4f46e5",
    secondary: "#6366f1",
    tertiary: "#818cf8",
    quaternary: "#a5b4fc",
  },
  {
    name: "synthwave",
    primary: "#e879f9",
    secondary: "#c084fc",
    tertiary: "#a855f7",
    quaternary: "#9333ea",
  },
  {
    name: "retro",
    primary: "#fca311",
    secondary: "#e5e5e5",
    tertiary: "#14213d",
    quaternary: "#000000",
  },
  {
    name: "cyberpunk",
    primary: "#ff007f",
    secondary: "#ff00ff",
    tertiary: "#00ffff",
    quaternary: "#0f0f0f",
  },
  {
    name: "valentine",
    primary: "#ffafcc",
    secondary: "#ffc8dd",
    tertiary: "#bde0fe",
    quaternary: "#a2d2ff",
  },
  {
    name: "halloween",
    primary: "#ff7518",
    secondary: "#ffb347",
    tertiary: "#8b0000",
    quaternary: "#3d0000",
  },
  {
    name: "garden",
    primary: "#2e7d32",
    secondary: "#388e3c",
    tertiary: "#43a047",
    quaternary: "#66bb6a",
  },
  {
    name: "forest",
    primary: "#0b6623",
    secondary: "#1b5e20",
    tertiary: "#2e7d32",
    quaternary: "#388e3c",
  },
  {
    name: "aqua",
    primary: "#00ffff",
    secondary: "#00e5ff",
    tertiary: "#00bcd4",
    quaternary: "#0097a7",
  },
  {
    name: "lofi",
    primary: "#e0e0e0",
    secondary: "#bdbdbd",
    tertiary: "#9e9e9e",
    quaternary: "#757575",
  },
  {
    name: "pastel",
    primary: "#ffcbf2",
    secondary: "#f3c4fb",
    tertiary: "#ecbcfd",
    quaternary: "#e5b3fe",
  },
  {
    name: "fantasy",
    primary: "#6a0dad",
    secondary: "#a100ff",
    tertiary: "#c850c0",
    quaternary: "#ff77ff",
  },
  {
    name: "wireframe",
    primary: "#ffffff",
    secondary: "#cccccc",
    tertiary: "#888888",
    quaternary: "#444444",
  },
  {
    name: "black",
    primary: "#000000",
    secondary: "#1a1a1a",
    tertiary: "#333333",
    quaternary: "#4d4d4d",
  },
  {
    name: "luxury",
    primary: "#b89f7c",
    secondary: "#8a7f66",
    tertiary: "#5e503f",
    quaternary: "#3b2e2c",
  },
  {
    name: "dracula",
    primary: "#ff79c6",
    secondary: "#bd93f9",
    tertiary: "#ffb86c",
    quaternary: "#6272a4",
  },
  {
    name: "cmyk",
    primary: "#00ffff",
    secondary: "#ff00ff",
    tertiary: "#ffff00",
    quaternary: "#000000",
  },
  {
    name: "autumn",
    primary: "#d2691e",
    secondary: "#ff7f50",
    tertiary: "#cd853f",
    quaternary: "#8b4513",
  },
  {
    name: "business",
    primary: "#1c3d5a",
    secondary: "#3b82f6",
    tertiary: "#60a5fa",
    quaternary: "#93c5fd",
  },
  {
    name: "acid",
    primary: "#ccff00",
    secondary: "#ff33cc",
    tertiary: "#00ff66",
    quaternary: "#3300cc",
  },
  {
    name: "lemonade",
    primary: "#f6e05e",
    secondary: "#faf089",
    tertiary: "#d69e2e",
    quaternary: "#b7791f",
  },
  {
    name: "night",
    primary: "#0f172a",
    secondary: "#1e293b",
    tertiary: "#334155",
    quaternary: "#475569",
  },
  {
    name: "coffee",
    primary: "#6f4e37",
    secondary: "#a67b5b",
    tertiary: "#c69c6d",
    quaternary: "#8b5a2b",
  },
  {
    name: "winter",
    primary: "#00bfff",
    secondary: "#87cefa",
    tertiary: "#4682b4",
    quaternary: "#5f9ea0",
  },
  {
    name: "dim",
    primary: "#2c2c2c",
    secondary: "#3c3c3c",
    tertiary: "#4d4d4d",
    quaternary: "#5f5f5f",
  },
  {
    name: "nord",
    primary: "#2e3440",
    secondary: "#3b4252",
    tertiary: "#434c5e",
    quaternary: "#4c566a",
  },
  {
    name: "sunset",
    primary: "#ff7e5f",
    secondary: "#feb47b",
    tertiary: "#f9d423",
    quaternary: "#fc913a",
  },
];
